### ISSUE TITLE
ChromeDriver with Docker

### ISSUE THREAD

**Issue by zfletch** [TheGnarCo/gnarails#36]
See [this comment](https://github.com/TheGnarCo/gnarails/pull/34#discussion_r143223932).

Feature specs don't work with Docker. You should be able to write a test with `js: true` and run `docker-compose run web rspec` successfully. What happens instead is that you get this error message:

```
Selenium::WebDriver::Error::WebDriverError:
   Unable to find chromedriver. Please download the server from http://chromedriver.storage.googleapis.com/index.html and place it somewhere on your PATH. More info at https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver.
```

EEC's [Dockerfile](https://github.com/TheGnarCo/eec-web/blob/9a94921743de0da53afd1c5fa3c36f2d50796699/Dockerfile#L13) has some lines about ChromeDriver which could be useful.

**Comment by BlakeWilliams** [comment]
Do we want the `Dockerfile` to support running the app in development/test? Personally I've never found that to be a productive environment and I know a decent amount of folks have the same sentiment. That being said, is this closable?

cc @kevin-j-m

**Comment by kevin-j-m** [comment]
I personally don't find that to be a desirable state (I don't want to, nor do I, run tests inside my docker container), yet I am but one person. I get the generic appeal, but I don't think it *actually* helps very much.

**Comment by BlakeWilliams** [comment]
Okay, thoughts on closing this until someone shows interest or opens a PR?

**Comment by kevin-j-m** [comment]
As always, issues and PRs are welcome.
